// Generated by scripts/generate_tokens.py. Edit tokens/feedback.tokens.json.
package com.gearui.foundation.motion

import com.tencent.kuikly.compose.animation.core.CubicBezierEasing
import com.gearui.foundation.material.TokenTransition

internal object FeedbackDefaults {
    val pressDuration = 300
    val highlightDuration = 200
    val pressScale = 0.985f
    val referenceWidth = 300f
    val highlightOpacity = 1f
    val disabledOpacity = 0.5f
    val pressEasing = CubicBezierEasing(0f, 0f, 0.58f, 1f)
    val neutralMix = 0.04f
    val accentMix = 0.1f
    val transparentHighlightOpacity = 0.3f
    val selectIndicatorDamping = 140f
    val selectIndicatorStiffness = 1000f
    val selectIndicatorMass = 4f
    val selectIndicatorRotation = 180f
    val selectForegroundMix = 0.2f
    val tagSoftOpacity = 0.15f
    val tagAccentForegroundMix = 0.2f
    val tagSuccessForegroundMix = 0.3f
    val tagWarningForegroundMix = 0.35f
    val selectionPressScale = 0.96f
    val selectionPressDuration = 150
    val selectionRevealDuration = 100
    val selectionRevealScale = 0.8f
    val radioExitScale = 1.5f
    val radioRevealDuration = 300
    val switchColorDuration = 175
    val switchStiffness = 1600f
    val switchDamping = 120f
    val switchMass = 2f
    val switchEasing = CubicBezierEasing(0.25f, 0.1f, 0.25f, 1f)
    val sliderDragScale = 0.9f
    val sliderStiffness = 200f
    val sliderDamping = 15f
    val sliderMass = 0.5f
    val accordionIndicatorStiffness = 1000f
    val accordionIndicatorDamping = 140f
    val accordionMass = 4f
    val accordionLayoutStiffness = 1600f
    val accordionLayoutDamping = 140f
    val accordionRotation = 180f
    val accordionFadeDuration = 200
    val accordionEnterEasing = CubicBezierEasing(0f, 0f, 0.58f, 1f)
    val accordionExitEasing = CubicBezierEasing(0.42f, 0f, 1f, 1f)
    val accordionEnterTransition = TokenTransition(200, 0, CubicBezierEasing(0f, 0f, 0.58f, 1f))
    val accordionExitTransition = TokenTransition(200, 0, CubicBezierEasing(0.42f, 0f, 1f, 1f))
    val menuItemPressScale = 0.98f
    val menuItemPressDuration = 150
    val menuItemDangerPressOpacity = 0.1f
    val overlayEnterDuration = 200
    val overlayExitDuration = 150
    val dialogEnterScale = 0.96f
    val anchoredEnterScale = 0.97f
    val anchoredEnterTranslate = 12f
    val overlayEaseOut = CubicBezierEasing(0f, 0f, 0.58f, 1f)
    val overlayEaseIn = CubicBezierEasing(0.42f, 0f, 1f, 1f)
}
