// Generated by scripts/generate_tokens.py. Edit tokens/typography.tokens.json.
package com.gearui.theme

import com.gearui.foundation.typography.TextStyle
import com.tencent.kuikly.compose.ui.text.font.FontWeight
import com.tencent.kuikly.compose.ui.unit.sp

internal object TypographyProfiles {
    val Native = Typography(
        bodyExtraLarge = TextStyle(22.sp, 27.sp, FontWeight(400)),
        bodyExtraSmall = TextStyle(12.sp, 17.sp, FontWeight(400)),
        bodyLarge = TextStyle(20.sp, 25.sp, FontWeight(400)),
        bodyMedium = TextStyle(17.sp, 22.sp, FontWeight(400)),
        bodySmall = TextStyle(15.sp, 20.sp, FontWeight(400)),
        caption = TextStyle(12.sp, 17.sp, FontWeight(400)),
        displayLarge = TextStyle(60.sp, 72.sp, FontWeight(800)),
        displayMedium = TextStyle(46.sp, 55.sp, FontWeight(800)),
        headlineLarge = TextStyle(40.sp, 48.sp, FontWeight(800)),
        headlineMedium = TextStyle(28.sp, 34.sp, FontWeight(700)),
        headlineSmall = TextStyle(24.sp, 29.sp, FontWeight(700)),
        label = TextStyle(11.sp, 16.sp, FontWeight(400)),
        linkLarge = TextStyle(20.sp, 25.sp, FontWeight(400)),
        linkMedium = TextStyle(17.sp, 22.sp, FontWeight(400)),
        linkSmall = TextStyle(15.sp, 20.sp, FontWeight(400)),
        markExtraSmall = TextStyle(12.sp, 17.sp, FontWeight(600)),
        markLarge = TextStyle(20.sp, 25.sp, FontWeight(600)),
        markMedium = TextStyle(17.sp, 22.sp, FontWeight(600)),
        markSmall = TextStyle(15.sp, 20.sp, FontWeight(600)),
        titleExtraLarge = TextStyle(22.sp, 26.sp, FontWeight(700)),
        titleLarge = TextStyle(20.sp, 24.sp, FontWeight(600)),
        titleMedium = TextStyle(17.sp, 20.sp, FontWeight(600)),
        titleSmall = TextStyle(15.sp, 18.sp, FontWeight(600)),
    )

    val Web = Typography(
        bodyExtraLarge = TextStyle(18.sp, 27.sp, FontWeight(400)),
        bodyExtraSmall = TextStyle(13.sp, 20.sp, FontWeight(400)),
        bodyLarge = TextStyle(16.sp, 24.sp, FontWeight(400)),
        bodyMedium = TextStyle(15.sp, 23.sp, FontWeight(400)),
        bodySmall = TextStyle(14.sp, 21.sp, FontWeight(400)),
        caption = TextStyle(13.sp, 20.sp, FontWeight(400)),
        displayLarge = TextStyle(60.sp, 72.sp, FontWeight(800)),
        displayMedium = TextStyle(46.sp, 57.sp, FontWeight(800)),
        headlineLarge = TextStyle(40.sp, 50.sp, FontWeight(800)),
        headlineMedium = TextStyle(26.sp, 34.sp, FontWeight(700)),
        headlineSmall = TextStyle(22.sp, 30.sp, FontWeight(700)),
        label = TextStyle(12.sp, 18.sp, FontWeight(400)),
        linkLarge = TextStyle(16.sp, 24.sp, FontWeight(400)),
        linkMedium = TextStyle(15.sp, 23.sp, FontWeight(400)),
        linkSmall = TextStyle(14.sp, 21.sp, FontWeight(400)),
        markExtraSmall = TextStyle(13.sp, 20.sp, FontWeight(600)),
        markLarge = TextStyle(16.sp, 24.sp, FontWeight(600)),
        markMedium = TextStyle(15.sp, 23.sp, FontWeight(600)),
        markSmall = TextStyle(14.sp, 21.sp, FontWeight(600)),
        titleExtraLarge = TextStyle(18.sp, 25.sp, FontWeight(700)),
        titleLarge = TextStyle(16.sp, 23.sp, FontWeight(600)),
        titleMedium = TextStyle(15.sp, 22.sp, FontWeight(600)),
        titleSmall = TextStyle(14.sp, 21.sp, FontWeight(600)),
    )

}
