#!/usr/bin/env bash
set -euo pipefail

# Rule: the icon constants, `Icons.all`, and the shipped PNG assets are one set.
#
# All three drifted apart at once, from a single silent failure in the asset
# generation:
#
#   - nine constants were missing from `Icons.all`, so the gallery reported
#     100 icons against the 109 that existed and those nine were unbrowsable;
#   - `block.png` shipped with no constant naming it, so nothing could ever
#     draw it;
#   - eight icons got a PNG but no SVG, which nobody noticed because the PNG
#     path was the default — and the SVGs turned out to be Material Symbols
#     against Phosphor PNGs, two different icon libraries under one name.
#
# The SVGs are gone: Kuikly hands the URL to the platform image loader and
# neither Android nor iOS decodes SVG. Assets are generated by
# `scripts/gen_icons.py`, so this guard checks that the generated set, the
# constants and `Icons.all` still agree.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ICONS_KT="$ROOT_DIR/gearui-kit/src/commonMain/kotlin/com/gearui/components/icon/Icons.kt"
ASSETS="$ROOT_DIR/gearui-kit/src/commonMain/assets/icons"

tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT

grep -oE '^    const val [a-z_0-9]+' "$ICONS_KT" | awk '{print $3}' | sort -u > "$tmp/consts"
awk '/val all = listOf\(/,/^    \)/' "$ICONS_KT" \
  | grep -oE '^\s+[a-z_0-9]+' | tr -d ' ' | grep -v '^val$' | sort -u > "$tmp/all"
find "$ASSETS" -name '*.png' -exec basename {} .png \; | sort -u > "$tmp/png"

fail=0
report() { # label, file_a, file_b
  local missing; missing="$(comm -23 "$2" "$3" | tr '\n' ' ')"
  if [[ -n "${missing// /}" ]]; then echo "  $1: $missing"; fail=1; fi
}

echo "Icon registry:"
report "constants with no PNG asset"      "$tmp/consts" "$tmp/png"
report "PNG assets with no constant"      "$tmp/png"    "$tmp/consts"
report "constants missing from Icons.all" "$tmp/consts" "$tmp/all"
report "Icons.all entries with no constant" "$tmp/all"  "$tmp/consts"

if [[ $fail -ne 0 ]]; then
  echo
  echo "Rule: a constant, an entry in Icons.all and a 96px PNG, or none of them."
  exit 1
fi

stray="$(find "$ASSETS" -name '*.svg' | wc -l | tr -d ' ')"
if [[ "$stray" != "0" ]]; then
  echo "  $stray SVG assets present; the icon set is PNG only (see gen_icons.py)"
  exit 1
fi

echo "Icon registry guard passed. icons=$(wc -l < "$tmp/consts" | tr -d ' ')"
