// Generated by scripts/generate_tokens.py. Edit tokens/materials.tokens.json.
package com.gearui.foundation.material

import com.tencent.kuikly.compose.ui.graphics.Color
import com.tencent.kuikly.compose.ui.unit.Dp
import com.tencent.kuikly.compose.ui.unit.dp
import com.tencent.kuikly.compose.animation.core.CubicBezierEasing

import com.tencent.kuikly.compose.ui.graphics.StrokeCap

internal typealias TokenShadow = SurfaceShadow
internal typealias TokenBorder = SurfaceBorder
internal data class TokenTransition(val durationMillis: Int, val delayMillis: Int, val easing: CubicBezierEasing)

internal data class TokenGradientStop(val position: Float, val color: Color)

internal object MaterialDefaults {
    val darkField = listOf<TokenShadow>(TokenShadow(Color(0f, 0f, 0f, 0f), 0.dp, 0.dp, 0.dp, 0.dp, true))
    val darkOverlay = listOf<TokenShadow>(TokenShadow(Color(1f, 1f, 1f, 0.2f), 0.dp, 0.dp, 1.dp, 0.dp, true))
    val darkSurface = listOf<TokenShadow>(TokenShadow(Color(0f, 0f, 0f, 0f), 0.dp, 0.dp, 0.dp, 0.dp, true))
    val lightField = listOf<TokenShadow>(TokenShadow(Color(0f, 0f, 0f, 0.04f), 0.dp, 2.dp, 4.dp, 0.dp, false), TokenShadow(Color(0f, 0f, 0f, 0.06f), 0.dp, 1.dp, 2.dp, 0.dp, false), TokenShadow(Color(0f, 0f, 0f, 0.06f), 0.dp, 0.dp, 1.dp, 0.dp, false))
    val lightOverlay = listOf<TokenShadow>(TokenShadow(Color(0f, 0f, 0f, 0.02f), 0.dp, 2.dp, 8.dp, 0.dp, false), TokenShadow(Color(0f, 0f, 0f, 0.01f), 0.dp, -6.dp, 12.dp, 0.dp, false), TokenShadow(Color(0f, 0f, 0f, 0.03f), 0.dp, 14.dp, 28.dp, 0.dp, false))
    val lightSurface = listOf<TokenShadow>(TokenShadow(Color(0f, 0f, 0f, 0.04f), 0.dp, 2.dp, 4.dp, 0.dp, false), TokenShadow(Color(0f, 0f, 0f, 0.06f), 0.dp, 1.dp, 2.dp, 0.dp, false), TokenShadow(Color(0f, 0f, 0f, 0.06f), 0.dp, 0.dp, 1.dp, 0.dp, false))
    val pickerBottomMask = listOf<TokenGradientStop>(TokenGradientStop(0f, Color(1f, 1f, 1f, 0f)), TokenGradientStop(1f, Color(1f, 1f, 1f, 1f)))
    val pickerTopMask = listOf<TokenGradientStop>(TokenGradientStop(0f, Color(1f, 1f, 1f, 1f)), TokenGradientStop(1f, Color(1f, 1f, 1f, 0f)))
}
